obstacle_range: 3.0
raytrace_range: 4.0
footprint: [[0.30,0.17],[0.30,-0.17],[-0.30,-0.17],[-0.30,0.17]]
inflation_radius: 0.25
cost_scaling_factor: 5.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
